[package]
name = "wh2-luadb-kmm-launcher"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winreg = "0.8"
winapi = "0.3"
crossterm = "0.19.0"
lazy_static = "1.4.0"